# Generated by Django 5.0.6 on 2024-06-05 11:35

import fileAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileAdmin', '0002_remove_userfile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=fileAdmin.models.generateRandomFileName),
        ),
    ]
