# Generated by Django 5.0.6 on 2024-06-06 11:59

import fileAdmin.models
import fileAdmin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileAdmin', '0006_userfile_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=fileAdmin.models.generateRandomFileName, validators=[fileAdmin.validators.validate_file_extension, fileAdmin.validators.validate_file_size]),
        ),
    ]
