# Generated by Django 5.0.6 on 2024-06-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileAdmin', '0008_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
